
services:
  docker:
    image: docker
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: production
    ports:
      - 3001:3000
    command: ["node", "index.js"]
